import Link from "next/link";
import { Button } from "@/components/ui/button";
import { FileIcon, StarIcon } from "lucide-react";
import SideBar from "./sideBar";

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function DashboardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className="container mx-auto pt-6">
			<div className="flex gap-8">
				<SideBar />
				<div className="w-full">{children}</div>
			</div>
		</main>
	);
}
